// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one


INSERT INTO messages (
  content, status
) VALUES (
  $1, $2
)
RETURNING id, content, status, created_at, updated_at
`

type CreateMessageParams struct {
	Content string        `json:"content"`
	Status  MessageStatus `json:"status"`
}

// -- name: GetMessage :one
// SELECT * FROM messages
// WHERE id = $1 LIMIT 1;
// -- name: ListMessages :many
// SELECT * FROM messages
// ORDER BY created_at DESC;
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.Content, arg.Status)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
