// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
  content, status, user_id
) VALUES (
  $1, $2, $3
)
RETURNING id, content, status, created_at, updated_at, user_id
`

type CreateMessageParams struct {
	Content string        `json:"content"`
	Status  MessageStatus `json:"status"`
	UserID  string        `json:"user_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.Content, arg.Status, arg.UserID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const listMessagesByUser = `-- name: ListMessagesByUser :many

SELECT id, content, status, created_at, updated_at, user_id FROM messages
WHERE user_id = $1
ORDER BY created_at DESC
`

// -- name: GetMessage :one
// SELECT * FROM messages
// WHERE id = $1 LIMIT 1;
func (q *Queries) ListMessagesByUser(ctx context.Context, userID string) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
