// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// -- name: GetMessage :one
	// SELECT * FROM messages
	// WHERE id = $1 LIMIT 1;
	// -- name: ListMessages :many
	// SELECT * FROM messages
	// ORDER BY created_at DESC;
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
}

var _ Querier = (*Queries)(nil)
