// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	DeleteMessage(ctx context.Context, arg DeleteMessageParams) error
	GetCurrentMigrationVersion(ctx context.Context) (int32, error)
	InsertMigrationVersion(ctx context.Context, dollar_1 int32) error
	// -- name: GetMessage :one
	// SELECT * FROM messages
	// WHERE id = $1 LIMIT 1;
	ListMessagesByUser(ctx context.Context, userID string) ([]Message, error)
}

var _ Querier = (*Queries)(nil)
