// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schema_migrations.sql

package db

import (
	"context"
)

const getCurrentMigrationVersion = `-- name: GetCurrentMigrationVersion :one
SELECT COALESCE(MAX(version), -1)::int AS version
FROM schema_migrations
WHERE NOT dirty
`

func (q *Queries) GetCurrentMigrationVersion(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getCurrentMigrationVersion)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const insertMigrationVersion = `-- name: InsertMigrationVersion :exec
INSERT INTO schema_migrations (version, dirty)
VALUES ($1::int, FALSE)
`

func (q *Queries) InsertMigrationVersion(ctx context.Context, dollar_1 int32) error {
	_, err := q.db.Exec(ctx, insertMigrationVersion, dollar_1)
	return err
}
