// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
  content, status, user_id
) VALUES (
  $1, $2, $3
)
RETURNING id, content, status, created_at, updated_at, user_id
`

type CreateTaskParams struct {
	Content string     `json:"content"`
	Status  TaskStatus `json:"status"`
	UserID  string     `json:"user_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.Content, arg.Status, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1 AND user_id = $2
`

type DeleteTaskParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.UserID)
	return err
}

const listTasksByUser = `-- name: ListTasksByUser :many

SELECT id, content, status, created_at, updated_at, user_id FROM tasks
WHERE user_id = $1
ORDER BY created_at DESC
`

// -- name: GetTask :one
// SELECT * FROM tasks
// WHERE id = $1 LIMIT 1;
func (q *Queries) ListTasksByUser(ctx context.Context, userID string) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
